# Generated by Django 2.0.7 on 2019-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20190712_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Flatno',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
