# Generated by Django 2.0.7 on 2019-07-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20190714_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='flatno',
            field=models.TextField(blank=True),
        ),
    ]
