# Generated by Django 2.0.7 on 2019-07-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_auto_20190714_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Flatno',
        ),
    ]
